// API import route tests (unit-level - testing validation logic)
import { importFullProfile, importFromDirectory, type DirectoryImportResult } from '@/lib/api/import';
import { DirectoryImportCards, DirectoryImportOutcome, MappingPreviewList, SessionImportErrors } from '@/components/import/upload-step';
import type { ImportSession } from '@/lib/types/import';
import { ownerProfilePreviewReady, previewContactCsv, previewOwnerProfileCsv } from '@/lib/import/mapping-preview';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { displayedImportErrorCount } from '@/app/(app)/import/import-history';

describe('Import API', () => {
  it('shows source columns, destinations, examples, and ignored columns before contacts import', () => {
    const preview = previewContactCsv('Connections.csv',
      'LinkedIn export\nGenerated by LinkedIn\nFirst Name,Last Name,URL,Unused\nAda,Lovelace,https://linkedin.com/in/ada,ignored');
    expect(preview?.fields).toEqual(expect.arrayContaining([
      { source: 'first_name', destination: 'Contact first name', example: 'Ada' },
      { source: 'url', destination: 'LinkedIn URL', example: 'https://linkedin.com/in/ada' },
    ]));
    const html = renderToStaticMarkup(createElement(MappingPreviewList, { previews: [preview!] }));
    expect(html).toContain('Field mapping preview');
    expect(html).toContain('first_name');
    expect(html).toContain('Contact first name');
    expect(html).toContain('Ignored columns: unused');
    expect(previewContactCsv('Profile Summary.csv', 'Name\nAda')).toBeNull();
  });

  it('previews owner profile field mapping before version creation', () => {
    const preview = previewOwnerProfileCsv('Profile.csv', 'First Name,Websites,Ignored\nAda,https://example.org,x');
    expect(preview?.fields).toEqual(expect.arrayContaining([
      { source: 'first_name', destination: 'First name', example: 'Ada' },
      { source: 'websites', destination: 'Websites', example: 'https://example.org' },
    ]));
    expect(preview?.ignored).toEqual(['ignored']);
  });
  it('marks selective supplemental columns that the owner importer ignores', () => {
    const skills = previewOwnerProfileCsv('Skills.csv', 'Skill,Name,Extra\nPainting,Writing,x');
    expect(skills?.fields).toEqual([{ source: 'name', destination: 'Owner skill', example: 'Writing' }]);
    expect(skills?.ignored).toEqual(['skill', 'extra']);
    expect(previewOwnerProfileCsv('Skills.csv', 'Skill\nPainting')?.warning).toContain('name');
    expect(previewOwnerProfileCsv('Company Follows.csv', 'Company,Organization\nAcme,Other')?.ignored).toEqual(['company']);
    expect(previewOwnerProfileCsv('Email Addresses.csv', 'Email Address,Primary,Other\na@b.com,Yes,x')?.ignored).toEqual(['other']);
    expect(previewOwnerProfileCsv('Messages.csv', 'From,Content,Conversation ID\nAda,Hello,1')?.ignored).toEqual(['content']);
    expect(previewOwnerProfileCsv('Invitations.csv', 'Direction,From\nOUTGOING,Ada')?.ignored).toEqual(['from']);
    expect(previewOwnerProfileCsv('Registration.csv', 'Date\n2020-01-01')?.warning).toContain('registered_at');
    expect(previewOwnerProfileCsv('Messages.csv', 'Content\nHello')?.warning).toContain('from');
    expect(previewOwnerProfileCsv('Invitations.csv', 'From\nAda')?.warning).toContain('direction');
    expect(previewOwnerProfileCsv('Profile Summary.csv', 'Name\nAda')).toBeNull();
    expect(previewOwnerProfileCsv('Skills.csv', 'Name\nWriting\nPainting')?.rowsSampled).toBe(1);
  });
  it('allows a valid Profile.csv with a malformed supplemental owner CSV', () => {
    const profile = previewOwnerProfileCsv('Profile.csv', 'First Name,Last Name\nAda,Lovelace')!;
    const malformed = previewOwnerProfileCsv('Registration.csv', 'Date\n2020-01-01')!;
    expect(malformed.warningDisposition).toBe('skip');
    expect(ownerProfilePreviewReady([profile, malformed], 2)).toBe(true);
    expect(renderToStaticMarkup(createElement(MappingPreviewList, { previews: [malformed] })))
      .toContain('This file will be skipped');
    expect(ownerProfilePreviewReady([previewOwnerProfileCsv('Profile.csv', 'First Name\n')!, malformed], 2)).toBe(false);
  });
  it('renders file and row errors for completed and failed sessions with a bounded total', () => {
    const session = {
      status: 'completed', errors: [{ file: 'Connections.csv', row: 9, message: 'Invalid date' }],
      errorTotal: 25, erroredRecords: 25, error: 'Invalid date',
    } as ImportSession;
    const html = renderToStaticMarkup(createElement(SessionImportErrors, { session }));
    expect(html).toContain('Connections.csv row 9: Invalid date');
    expect(html).toContain('Showing 1 of 25 errors');
    const failed = renderToStaticMarkup(createElement(SessionImportErrors, { session: { ...session, status: 'failed' } }));
    expect(failed).toContain('Connections.csv row 9: Invalid date');
    expect(renderToStaticMarkup(createElement(SessionImportErrors, { session: { ...session, errors: [], errorTotal: 0, erroredRecords: 0, error: null } }))).toBe('');
  });
  it('uses the directory route field names in all four visible result cards', async () => {
    const fixture: DirectoryImportResult = {
      status: 'completed',
      totalRecords: 20, newRecords: 7, updatedRecords: 5, skippedRecords: 6,
      errorCount: 2, errors: [{ file: 'Connections.csv', row: 9, message: 'Invalid date' }],
      recognizedFiles: ['Connections.csv'], skippedFiles: [],
    };
    const fetchMock = jest.spyOn(global, 'fetch').mockResolvedValue({
      ok: true, json: async () => fixture,
    } as Response);
    try {
      const result = await importFromDirectory('/data/export', 'self-id');
      const html = renderToStaticMarkup(createElement(DirectoryImportCards, { result }));
      for (const [count, label] of [[7, 'New'], [5, 'Updated'], [6, 'Skipped'], [2, 'Errors']]) {
        expect(html).toContain(`>${count}</p><p class="text-xs text-muted-foreground">${label}</p>`);
      }
      expect(html).not.toContain('undefined');
    } finally {
      fetchMock.mockRestore();
    }
  });
  it('shows failed directory imports with partial counts instead of a success claim', () => {
    const result: DirectoryImportResult = {
      status: 'failed', totalRecords: 4, newRecords: 1, updatedRecords: 0,
      skippedRecords: 3, errorCount: 1, errors: [{ file: 'Messages.csv', message: 'Missing owner name' }],
      recognizedFiles: ['Messages.csv'],
    };
    const html = renderToStaticMarkup(createElement(DirectoryImportOutcome, { result }));
    expect(html).toContain('Import Failed');
    expect(html).toContain('1 record imported before failure; 3 skipped');
    expect(html).not.toContain('Import Complete');
    expect(renderToStaticMarkup(createElement(DirectoryImportOutcome, { result, contacts: true })))
      .toContain('Contacts Import Failed');
  });
  it('shows file and row errors in the owner-result contacts outcome', () => {
    const result: DirectoryImportResult = {
      status: 'completed', totalRecords: 3, newRecords: 1, updatedRecords: 0,
      skippedRecords: 2, errorCount: 2,
      errors: [
        { file: 'Connections.csv', row: 3, message: 'Invalid LinkedIn profile URL' },
        { file: 'Messages.csv', message: 'Owner name unavailable' },
      ],
      recognizedFiles: ['Connections.csv', 'Messages.csv'], skippedFiles: [],
    };
    const html = renderToStaticMarkup(createElement(DirectoryImportOutcome, { result, contacts: true }));
    expect(html).toContain('Contacts Imported');
    expect(html).toContain('Connections.csv row 3: Invalid LinkedIn profile URL');
    expect(html).toContain('Messages.csv: Owner name unavailable');
    expect(html).toContain('Directory import errors');
  });
  it('displays appended and failed-upload errors even for stale historical counts', () => {
    expect(displayedImportErrorCount({ error_count: 0, errors: [{ message: 'Post-import failure' }] })).toBe(1);
    expect(displayedImportErrorCount({ error_count: 0, errors: [{ message: 'Upload failed before processing' }] })).toBe(1);
  });
  it('unwraps a successful full-profile response for the result view', async () => {
    const response = { profileId: 'profile-1', version: 2, selfName: 'Ada Lovelace',
      importedFiles: ['Profile.csv'], skippedFiles: [], totalFiles: 1 };
    const fetchMock = jest.spyOn(global, 'fetch').mockResolvedValue({
      ok: true, json: async () => ({ data: response }),
    } as Response);
    try {
      await expect(importFullProfile('/export')).resolves.toEqual(response);
      expect(fetchMock).toHaveBeenCalledWith('/api/import/full-profile', expect.objectContaining({ method: 'POST' }));
    } finally {
      fetchMock.mockRestore();
    }
  });
  const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
  const MAX_FILE_SIZE = 50 * 1024 * 1024;

  describe('file validation', () => {
    it('should only accept .csv files', () => {
      const validFiles = ['Connections.csv', 'messages.csv', 'Education.CSV'];
      const invalidFiles = ['data.json', 'script.js', 'image.png', 'archive.zip'];

      for (const f of validFiles) {
        expect(f.toLowerCase().endsWith('.csv')).toBe(true);
      }
      for (const f of invalidFiles) {
        expect(f.toLowerCase().endsWith('.csv')).toBe(false);
      }
    });

    it('should reject files over 50 MB', () => {
      const fileSize = 60 * 1024 * 1024;
      expect(fileSize > MAX_FILE_SIZE).toBe(true);

      const validSize = 10 * 1024 * 1024;
      expect(validSize > MAX_FILE_SIZE).toBe(false);
    });
  });

  describe('session ID validation', () => {
    it('should accept valid session UUIDs', () => {
      expect(UUID_REGEX.test('550e8400-e29b-41d4-a716-446655440000')).toBe(true);
    });

    it('should reject invalid session IDs', () => {
      expect(UUID_REGEX.test('not-valid')).toBe(false);
      expect(UUID_REGEX.test('')).toBe(false);
    });
  });

  describe('processing request validation', () => {
    it('should require sessionId', () => {
      const body = {};
      const hasSessionId = 'sessionId' in body;
      expect(hasSessionId).toBe(false);
    });

    it('should require selfContactId', () => {
      const body = { sessionId: '550e8400-e29b-41d4-a716-446655440000' };
      const hasSelfId = 'selfContactId' in body;
      expect(hasSelfId).toBe(false);
    });
  });

  describe('status response format', () => {
    it('should include required fields', () => {
      const mockSession = {
        id: '550e8400-e29b-41d4-a716-446655440000',
        status: 'processing',
        total_files: 3,
        processed_files: 1,
        total_records: 100,
        new_records: 80,
        updated_records: 15,
        skipped_records: 5,
        error_count: 0,
        errors: [],
        started_at: new Date(),
        completed_at: null,
        created_at: new Date(),
      };

      expect(mockSession).toHaveProperty('status');
      expect(mockSession).toHaveProperty('total_files');
      expect(mockSession).toHaveProperty('processed_files');
      expect(mockSession).toHaveProperty('total_records');
      expect(mockSession).toHaveProperty('new_records');
      expect(mockSession).toHaveProperty('error_count');
    });
  });
});
